const out = {};
await refresh();
await loadCatalog({ refresh: false });
out.games = catalog.games.length;
out.installed = catalog.games.filter((g) => installedFor(g)).map((g) => g.title);
showView("foryou"); await wait(800);
const heads = (id) => [...$(id).querySelectorAll(".group-head")].map((h) => h.textContent);
out.forYou = { heads: heads("forYouList"), cards: $("forYouList").querySelectorAll(".gtile").length };
showView("new"); await wait(800);
out.newGames = { heads: heads("newList"), cards: $("newList").querySelectorAll(".gtile").length };
showView("browse"); await wait(800);
out.browseShelves = document.querySelectorAll("#browse .newshelf, #newShelf, #becauseShelf").length;
out.quietBadges = document.querySelectorAll("#catalogList .badge").length ? [...document.querySelectorAll("#catalogList .badge")].filter((b) => /No Release Since/.test(b.textContent)).length : 0;
await digestCheck(); await renderLibrary(); await wait(300);
out.digest = $("digestPanel").hidden ? "hidden" : $("digestPanel").textContent.replace(/\s+/g, " ").trim();
const hg = catalog.games.find((g) => g.id === "github:florinp93/hells-gate-recomp");
await showDetail(hg); await wait(3000);
out.funding = $("detailFunding").textContent.replace(/\s+/g, " ").trim();
out.detailExtras = ["detailNotes", "detailVotes"].filter((id) => $(id)).concat([...document.querySelectorAll("#detail h3")].map((h) => h.textContent).filter((t) => /Was It Good|Your Notes/.test(t)));
return { ok: out.forYou.cards > 0 && /^Because You Have/.test(out.forYou.heads[0] || "") && out.newGames.cards > 0 && !out.browseShelves && out.digest !== "hidden" && /Ko-fi/.test(out.funding) && !out.detailExtras.length, ...out };
